version:            '2'
services:
  mws_graphql:
    container_name:
      "mws_graphql"
    build:
      context:      ./server/graphql
    image:
      "mws_graphql"
    ports:
      - "4002:4001"
    restart:        unless-stopped
  mws_solr:
    container_name:
      "mws_solr"
    build:
      context:      ./server/solr
    image:
      "mws_solr"
    ports:
      - "8985:8983"
    environment:
      - SOLR_OPTS=-Xmx5g
    restart:        unless-stopped
